site_name: OKD.io
site_description: >-
  The Community Distribution of Kubernetes that powers Red Hat OpenShift
site_url: https://openshift-cs.github.io/okd.io/index.html
site_author: Brian Innes
repo_name: "okd-io"
repo_url: https://github.com/okd-project/okd.io
docs_dir: docs
site_dir: public
edit_uri: edit/main/docs
theme:
  name: material
  logo: img/okd_logo_resized.svg
  favicon: img/okdLogo.png
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: okd
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
      primary: blue grey
      accent: red
    - media: "(prefers-color-scheme: dark)"
      scheme: okd-dark
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
      primary: okd blue
      accent: okd light green
  font:
    text: Open Sans
    code: Roboto Mono
  language: en
  custom_dir: overrides
  features:
    - content.code.copy
    - content.code.annotate
    # - content.tabs.link
    # - -
    - naviagation.sections
    - navigation.tracking
    # - navigation.tabs
    # - navigation.tabs.sticky
    # - navigation.top
    - search.suggest
    - search.highlight
use_directory_urls: true
plugins:
  - tags
  - social
  - blog:
      archive: true
      archive_date_format: yyyy
      archive_url_date_format: yyyy
      authors: true
      authors_file: "{blog}/.authors.yml"
      blog_dir: blog
      blog_toc: true
      categories: false
      categories_allowed:
        - Build
        - Community
        - Testing
        - Guide
      categories_name: Categories
      categories_slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
      post_url_date_format: yyyy/MM/dd
      post_url_format: "{date}/{slug}"
      post_slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
      post_slugify_separator: _
      post_excerpt: optional
      post_excerpt_max_authors: 2
  - minify:
      minify_html: true
  - search:
      pipeline:
        - stemmer
        - stopWordFilter
        - trimmer
markdown_extensions:
  - attr_list
  - admonition
  - toc:
      permalink: true
      toc_depth: 4
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.highlight
  - pymdownx.tabbed
  - pymdownx.details
extra_css:
  - css/extra.css
extra:
  generator: false
copyright: Copyright Â© 2022 OKD Working Group
nav:
  - Home: index.md
  - About: about.md
  - Getting Started:
      - Installation: installation.md
      - CRC: crc.md
  - Documentation: docs.md
  - Blog: 
      - blog/index.md
  - Community:
      - OKD Community: community.md
      - Code of Conduct: conduct.md
      - Contributor: contributor.md
  - OKD Working Group:
      - About: working-groups.md
      - Charter: charter.md
      - Communications: communications.md
      - Minutes: working-group/minutes/minutes.md
      - Subgroups:
          - Documentation:
              - Overview: wg_docs/overview.md
              - Modifying OKD.io: wg_docs/okd-io.md
              - Setup environment: wg_docs/doc-env.md
              - Content guidelines: wg_docs/content.md
          - CRC Build:
              - Overview: wg_crc/overview.md
          - OKD Virtualization:
              - Overview: wg_virt/overview.md
              - Community: wg_virt/community.md
  - OKD Development:
      - Overview: okd_tech_docs/index.md
      - Modifying OKD: okd_tech_docs/modifying_okd.md
      - Operator Hub catalogs: okd_tech_docs/operators.md
      - Release: okd_tech_docs/release.md
      - Troubleshooting: okd_tech_docs/troubleshoot.md
  - Help:
      - Getting Help: help.md
      - FAQ: faq.md
